name: "Build image job"
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build image job
    steps:
      - name: Checkout master
        uses: actions/checkout@master
      - name: Build and publish image
        uses: ilteoood/docker_buildx@master
        with:
          publish: true
          imageName: q123458384/jd
          dockerFile: docker/Dockerfile
          platform: linux/amd64,linux/arm64,linux/arm/v6,linux/arm/v7 # 你准备构建的镜像平台
          tag: latest
          dockerUser: ${{ secrets.DOCKER_USERNAME }} # docker hub userid 在setting创建secrets name=DOCKER_USERNAME  value=dockerid
          dockerPassword: ${{ secrets.DOCKER_PASSWORD }} # docker hub password,在setting创建secrets name=DOCKER_PASSWORD  value=dockerpassword